[2021-05-31 10:08:53,288] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-05-31 10:18:53,288] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-05-31 10:28:53,288] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-05-31 10:38:53,288] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-05-31 10:48:53,288] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-05-31 10:54:17,230] INFO [GroupCoordinator 0]: Member 150c32c8-b6c3-4cc0-a94c-c68e0105ab2e-23a386b0-dba4-4d47-8aeb-b7c487f8095b in group LogService has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-05-31 10:54:17,230] INFO [GroupCoordinator 0]: Preparing to rebalance group LogService in state PreparingRebalance with old generation 2 (__consumer_offsets-49) (reason: removing member 150c32c8-b6c3-4cc0-a94c-c68e0105ab2e-23a386b0-dba4-4d47-8aeb-b7c487f8095b on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-05-31 10:54:17,232] INFO [GroupCoordinator 0]: Group LogService with generation 3 is now empty (__consumer_offsets-49) (kafka.coordinator.group.GroupCoordinator)
[2021-05-31 10:54:17,902] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-05-31 10:54:17,907] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2021-05-31 10:54:17,912] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2021-05-31 10:54:18,247] WARN Session 0x100100031750000 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Conexão fechada pela outra ponta
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2021-05-31 10:54:18,354] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2021-05-31 10:54:18,355] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2021-05-31 10:54:20,293] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:20,294] INFO Socket error occurred: localhost/127.0.0.1:2181: Conexão recusada (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:20,395] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2021-05-31 10:54:22,071] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:22,072] INFO Socket error occurred: localhost/127.0.0.1:2181: Conexão recusada (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:23,635] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:23,636] INFO Socket error occurred: localhost/127.0.0.1:2181: Conexão recusada (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:25,601] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:25,602] INFO Socket error occurred: localhost/127.0.0.1:2181: Conexão recusada (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:27,265] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:27,266] INFO Socket error occurred: localhost/127.0.0.1:2181: Conexão recusada (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:28,754] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:28,754] INFO Socket error occurred: localhost/127.0.0.1:2181: Conexão recusada (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:30,816] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:30,817] INFO Socket error occurred: localhost/127.0.0.1:2181: Conexão recusada (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:32,691] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-31 10:54:32,692] INFO Socket error occurred: localhost/127.0.0.1:2181: Conexão recusada (org.apache.zookeeper.ClientCnxn)
